export const data = [
  {
    image: "https://robohash.org/estdolorequos.png?size=100x100&set=set1",
    name: "Caesar Ringham",
    color: "Turquoise",
    hex_color: "#14249c",
    money: "$416.02",
    mobile: "Android 4.4.2",
  },
  {
    image:
      "https://robohash.org/blanditiisetvoluptatem.png?size=100x100&set=set1",
    name: "Randee Bartoleyn",
    color: "Fuscia",
    hex_color: "#d4de29",
    money: "$387.93",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/isteautemvoluptas.png?size=100x100&set=set1",
    name: "Corinne Porrett",
    color: "Goldenrod",
    hex_color: "#367651",
    money: "$618.00",
    mobile: "Android 4.2",
  },
  {
    image:
      "https://robohash.org/voluptatesnonconsequatur.png?size=100x100&set=set1",
    name: "Orv Scholard",
    color: "Violet",
    hex_color: "#748ea3",
    money: "$354.99",
    mobile: "Microsoft Windows Phone 8.1",
  },
  {
    image: "https://robohash.org/remvoluptasquidem.png?size=100x100&set=set1",
    name: "Emylee Kemson",
    color: "Puce",
    hex_color: "#237b9d",
    money: "$584.55",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/exsuscipitdolores.png?size=100x100&set=set1",
    name: "Job Innocenti",
    color: "Yellow",
    hex_color: "#299b84",
    money: "$224.35",
    mobile: "Android 6.0",
  },
  {
    image: "https://robohash.org/quiavoluptatesaut.png?size=100x100&set=set1",
    name: "Donaugh Doughill",
    color: "Fuscia",
    hex_color: "#f593df",
    money: "$966.02",
    mobile: "Android 6.0",
  },
  {
    image: "https://robohash.org/quoetperspiciatis.png?size=100x100&set=set1",
    name: "Rozalin Butson",
    color: "Khaki",
    hex_color: "#b1ca4d",
    money: "$258.07",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/dictaomnisea.png?size=100x100&set=set1",
    name: "Jamil Casperri",
    color: "Violet",
    hex_color: "#057ca4",
    money: "$462.15",
    mobile: "iOS, up to iOS 3.1.3",
  },
  {
    image: "https://robohash.org/temporadolorescum.png?size=100x100&set=set1",
    name: "Nananne Reames",
    color: "Purple",
    hex_color: "#cf8996",
    money: "$825.30",
    mobile: "Android 4, Sense UI 4",
  },
  {
    image:
      "https://robohash.org/laudantiumcorruptipossimus.png?size=100x100&set=set1",
    name: "Albertina Burdge",
    color: "Fuscia",
    hex_color: "#00a81d",
    money: "$547.33",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/quinullaquis.png?size=100x100&set=set1",
    name: "Araldo Piddletown",
    color: "Goldenrod",
    hex_color: "#9c3b45",
    money: "$58.77",
    mobile: "Android 5.0, up to 6.0",
  },
  {
    image: "https://robohash.org/eumsedmaxime.png?size=100x100&set=set1",
    name: "Joyous Weinham",
    color: "Violet",
    hex_color: "#d412a8",
    money: "$616.78",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/autdolorfacere.png?size=100x100&set=set1",
    name: "Lonnie Breakwell",
    color: "Goldenrod",
    hex_color: "#edc143",
    money: "$395.28",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/optioaliasrerum.png?size=100x100&set=set1",
    name: "Travers Johantges",
    color: "Turquoise",
    hex_color: "#d433df",
    money: "$825.01",
    mobile: "Android 5.1, EMUI 3.1",
  },
  {
    image: "https://robohash.org/similiquealiquamut.png?size=100x100&set=set1",
    name: "Rosy Eddies",
    color: "Red",
    hex_color: "#88541e",
    money: "$560.35",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/autnullaaut.png?size=100x100&set=set1",
    name: "Wilbur Hynd",
    color: "Puce",
    hex_color: "#729865",
    money: "$325.73",
    mobile: "Microsoft Windows Phone 7.8",
  },
  {
    image: "https://robohash.org/architectoautquam.png?size=100x100&set=set1",
    name: "Kayle Breissan",
    color: "Fuscia",
    hex_color: "#aece21",
    money: "$515.85",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/omnisquidemrem.png?size=100x100&set=set1",
    name: "Hazlett Hansman",
    color: "Mauv",
    hex_color: "#fd8b33",
    money: "$870.50",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/perferendissolutalaudantium.png?size=100x100&set=set1",
    name: "Beverlie Fowles",
    color: "Purple",
    hex_color: "#cf1bbb",
    money: "$379.13",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/sitquaset.png?size=100x100&set=set1",
    name: "Fulvia Ivshin",
    color: "Khaki",
    hex_color: "#58b223",
    money: "$248.50",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/omnisrationemolestias.png?size=100x100&set=set1",
    name: "Hillie Sandeson",
    color: "Khaki",
    hex_color: "#47b184",
    money: "$44.17",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/voluptatumdeseruntnisi.png?size=100x100&set=set1",
    name: "Lind Kealey",
    color: "Violet",
    hex_color: "#418d1a",
    money: "$735.33",
    mobile: "Android 7.0",
  },
  {
    image:
      "https://robohash.org/corruptiliberofacilis.png?size=100x100&set=set1",
    name: "Cass Zuan",
    color: "Puce",
    hex_color: "#05fe81",
    money: "$663.57",
    mobile: "Android 7, ZenUI 4",
  },
  {
    image:
      "https://robohash.org/cumquedistinctionecessitatibus.png?size=100x100&set=set1",
    name: "Burt Rohmer",
    color: "Violet",
    hex_color: "#411d55",
    money: "$438.05",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/culpaverocorrupti.png?size=100x100&set=set1",
    name: "Nadeen Parratt",
    color: "Goldenrod",
    hex_color: "#ab31a4",
    money: "$62.13",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/nemoatest.png?size=100x100&set=set1",
    name: "Rutherford Yglesia",
    color: "Crimson",
    hex_color: "#218ae6",
    money: "$774.10",
    mobile: "Android 7.0",
  },
  {
    image:
      "https://robohash.org/impeditmagnamarchitecto.png?size=100x100&set=set1",
    name: "Foss Naris",
    color: "Blue",
    hex_color: "#32ad62",
    money: "$523.05",
    mobile: "Android 7.0",
  },
  {
    image: "https://robohash.org/omnisnostrumdolorem.png?size=100x100&set=set1",
    name: "Nan Kendell",
    color: "Green",
    hex_color: "#5bc3d1",
    money: "$895.96",
    mobile: "iOS 12.1.3, up to iPadOS 14.6",
  },
  {
    image: "https://robohash.org/liberovoluptateest.png?size=100x100&set=set1",
    name: "Henriette Wroth",
    color: "Aquamarine",
    hex_color: "#84c196",
    money: "$754.96",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/suntadsit.png?size=100x100&set=set1",
    name: "Gian Danaher",
    color: "Puce",
    hex_color: "#952043",
    money: "$436.05",
    mobile: "Android 9.0, up to Android 11, One UI 3.0",
  },
  {
    image: "https://robohash.org/expeditailloitaque.png?size=100x100&set=set1",
    name: "Luciano Weightman",
    color: "Yellow",
    hex_color: "#6c88a9",
    money: "$424.27",
    mobile: "Android 5.1.1",
  },
  {
    image: "https://robohash.org/rerumquaeratet.png?size=100x100&set=set1",
    name: "Selestina Foord",
    color: "Maroon",
    hex_color: "#0dac49",
    money: "$21.22",
    mobile: "Android OS, Sense UI",
  },
  {
    image: "https://robohash.org/reiciendisverosaepe.png?size=100x100&set=set1",
    name: "Edna Wren",
    color: "Maroon",
    hex_color: "#c53ea8",
    money: "$735.31",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/attemporibussuscipit.png?size=100x100&set=set1",
    name: "Wiatt Guinnane",
    color: "Teal",
    hex_color: "#c67897",
    money: "$947.23",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/quisapientevel.png?size=100x100&set=set1",
    name: "Twila Clace",
    color: "Red",
    hex_color: "#38fd04",
    money: "$867.73",
    mobile: "Android 7.0",
  },
  {
    image: "https://robohash.org/nemonatusfuga.png?size=100x100&set=set1",
    name: "Elston Coram",
    color: "Puce",
    hex_color: "#8b34df",
    money: "$706.25",
    mobile: "Android 10, up to Android 11, Realme UI 2.0",
  },
  {
    image: "https://robohash.org/eaqueremitaque.png?size=100x100&set=set1",
    name: "Krystal Lenz",
    color: "Orange",
    hex_color: "#31f552",
    money: "$956.30",
    mobile: "Android 7.1",
  },
  {
    image: "https://robohash.org/rerumfugaharum.png?size=100x100&set=set1",
    name: "Cairistiona Kipping",
    color: "Mauv",
    hex_color: "#6e0106",
    money: "$636.11",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/dignissimosdelectuset.png?size=100x100&set=set1",
    name: "Marcellus Leason",
    color: "Crimson",
    hex_color: "#c140af",
    money: "$778.53",
    mobile: "Android 9.0",
  },
  {
    image: "https://robohash.org/autipsumblanditiis.png?size=100x100&set=set1",
    name: "Halie Hadley",
    color: "Violet",
    hex_color: "#87601f",
    money: "$637.65",
    mobile: "Android 4.0",
  },
  {
    image:
      "https://robohash.org/consequaturdelectussit.png?size=100x100&set=set1",
    name: "Edd enzley",
    color: "Pink",
    hex_color: "#5a9e9d",
    money: "$201.87",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/animiprovidentdolorem.png?size=100x100&set=set1",
    name: "Fidelia Skryne",
    color: "Maroon",
    hex_color: "#7e85d3",
    money: "$381.26",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/utvoluptatedelectus.png?size=100x100&set=set1",
    name: "Mal Gibb",
    color: "Pink",
    hex_color: "#f05c5d",
    money: "$642.01",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/doloresremharum.png?size=100x100&set=set1",
    name: "Luca Gimert",
    color: "Goldenrod",
    hex_color: "#d8b8d7",
    money: "$623.21",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/dolorumdistinctioconsequuntur.png?size=100x100&set=set1",
    name: "Rosalind Giddins",
    color: "Red",
    hex_color: "#a56da0",
    money: "$766.64",
    mobile: "Android 4.4.2",
  },
  {
    image: "https://robohash.org/possimusquoslabore.png?size=100x100&set=set1",
    name: "Luciana Prior",
    color: "Blue",
    hex_color: "#317f32",
    money: "$419.86",
    mobile: "Android 6.0.1",
  },
  {
    image: "https://robohash.org/maioresabfacere.png?size=100x100&set=set1",
    name: "Bastian Coal",
    color: "Fuscia",
    hex_color: "#f553b1",
    money: "$717.10",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/etcommodinihil.png?size=100x100&set=set1",
    name: "Jo Gilkes",
    color: "Mauv",
    hex_color: "#947637",
    money: "$808.48",
    mobile: "Android 8.1 Oreo",
  },
  {
    image: "https://robohash.org/sedametnatus.png?size=100x100&set=set1",
    name: "Amy Floch",
    color: "Turquoise",
    hex_color: "#80d081",
    money: "$71.80",
    mobile: "Android 10, ColorOS 7.1",
  },
  {
    image: "https://robohash.org/voluptaseiusquae.png?size=100x100&set=set1",
    name: "Con Deakins",
    color: "Violet",
    hex_color: "#8da387",
    money: "$241.62",
    mobile: "Android 6.1, up to Android 8, Funtouch 3",
  },
  {
    image: "https://robohash.org/doloremquisdicta.png?size=100x100&set=set1",
    name: "Robinetta Ceaser",
    color: "Pink",
    hex_color: "#a38e23",
    money: "$252.68",
    mobile: "Android 7.0",
  },
  {
    image: "https://robohash.org/etveniamest.png?size=100x100&set=set1",
    name: "Garek Imason",
    color: "Violet",
    hex_color: "#cc4483",
    money: "$106.73",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/etsedofficiis.png?size=100x100&set=set1",
    name: "Ernestus Halkyard",
    color: "Violet",
    hex_color: "#d94a60",
    money: "$826.17",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/doloresautemdolore.png?size=100x100&set=set1",
    name: "Charline Sylvester",
    color: "Goldenrod",
    hex_color: "#0e9525",
    money: "$585.09",
    mobile: "Android 6.0, Flyme 7.3",
  },
  {
    image: "https://robohash.org/enimquiafacere.png?size=100x100&set=set1",
    name: "Ealasaid Sustin",
    color: "Aquamarine",
    hex_color: "#91d21b",
    money: "$788.42",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/aetblanditiis.png?size=100x100&set=set1",
    name: "Willette Spinks",
    color: "Indigo",
    hex_color: "#d8af7e",
    money: "$81.11",
    mobile: "Android 6.0",
  },
  {
    image: "https://robohash.org/odioquiacum.png?size=100x100&set=set1",
    name: "Mathe Guilbert",
    color: "Green",
    hex_color: "#e3ee49",
    money: "$30.51",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/adipisciconsequaturaperiam.png?size=100x100&set=set1",
    name: "Ellynn Patemore",
    color: "Indigo",
    hex_color: "#6034f7",
    money: "$831.87",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/undeetinventore.png?size=100x100&set=set1",
    name: "Constanta FitzGibbon",
    color: "Indigo",
    hex_color: "#582d31",
    money: "$532.37",
    mobile: "Android 4.0",
  },
  {
    image:
      "https://robohash.org/quaeratvoluptaseligendi.png?size=100x100&set=set1",
    name: "Lorenza Finlry",
    color: "Goldenrod",
    hex_color: "#9ad9f4",
    money: "$712.04",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/eosmaximelabore.png?size=100x100&set=set1",
    name: "Hedda Carreyette",
    color: "Goldenrod",
    hex_color: "#653516",
    money: "$142.11",
    mobile: "Android 4.1",
  },
  {
    image: "https://robohash.org/laudantiumautemet.png?size=100x100&set=set1",
    name: "Dorella Lockhart",
    color: "Green",
    hex_color: "#c83a16",
    money: "$741.73",
    mobile: "Android 7.0",
  },
  {
    image: "https://robohash.org/autsedvoluptas.png?size=100x100&set=set1",
    name: "Tomi Gosart",
    color: "Crimson",
    hex_color: "#1695da",
    money: "$814.39",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/odituteaque.png?size=100x100&set=set1",
    name: "Tedi Kristufek",
    color: "Mauv",
    hex_color: "#517e35",
    money: "$693.10",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/voluptatesquasqui.png?size=100x100&set=set1",
    name: "Gwen Aaronsohn",
    color: "Fuscia",
    hex_color: "#26ba23",
    money: "$996.57",
    mobile: "Android 4.4.2",
  },
  {
    image: "https://robohash.org/sitrempossimus.png?size=100x100&set=set1",
    name: "Tildi Manoch",
    color: "Fuscia",
    hex_color: "#c00396",
    money: "$68.64",
    mobile: "Android 4.4.4",
  },
  {
    image: "https://robohash.org/odioetasperiores.png?size=100x100&set=set1",
    name: "Rodolfo Normand",
    color: "Maroon",
    hex_color: "#cbcc0d",
    money: "$700.16",
    mobile: "Android 7.1",
  },
  {
    image:
      "https://robohash.org/dignissimosomnislaboriosam.png?size=100x100&set=set1",
    name: "Tedda Bewley",
    color: "Turquoise",
    hex_color: "#899ffd",
    money: "$25.57",
    mobile: "Android 4.4",
  },
  {
    image: "https://robohash.org/sitvitaeat.png?size=100x100&set=set1",
    name: "Tallulah Reddoch",
    color: "Maroon",
    hex_color: "#6dc2ca",
    money: "$898.95",
    mobile: "Android 5.0",
  },
  {
    image: "https://robohash.org/quaeratsintcum.png?size=100x100&set=set1",
    name: "Reagen Schustl",
    color: "Teal",
    hex_color: "#e9de9e",
    money: "$977.47",
    mobile: "Android 4.2.2",
  },
  {
    image: "https://robohash.org/errordolorumminus.png?size=100x100&set=set1",
    name: "Dolorita Moryson",
    color: "Puce",
    hex_color: "#53e13e",
    money: "$125.85",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/estfacerenisi.png?size=100x100&set=set1",
    name: "Evonne Sleep",
    color: "Teal",
    hex_color: "#b8722b",
    money: "$813.14",
    mobile: "Android 5.1, up to 7.1.1",
  },
  {
    image: "https://robohash.org/eumtemporamollitia.png?size=100x100&set=set1",
    name: "Odelinda Farmiloe",
    color: "Yellow",
    hex_color: "#e632bc",
    money: "$317.75",
    mobile: "Android 6.0",
  },
  {
    image: "https://robohash.org/autaccusamusin.png?size=100x100&set=set1",
    name: "Melony Spuffard",
    color: "Orange",
    hex_color: "#92c212",
    money: "$735.92",
    mobile: "Android 10, EMUI 10.1",
  },
  {
    image: "https://robohash.org/aperiamrationedicta.png?size=100x100&set=set1",
    name: "Darcie Idill",
    color: "Turquoise",
    hex_color: "#8451cb",
    money: "$535.22",
    mobile: "Android 7.0, 8.0, up to Android 9.0",
  },
  {
    image:
      "https://robohash.org/reprehenderitquodiste.png?size=100x100&set=set1",
    name: "Francoise Screen",
    color: "Maroon",
    hex_color: "#74e9ed",
    money: "$999.67",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/eaetenim.png?size=100x100&set=set1",
    name: "Ivett Monk",
    color: "Indigo",
    hex_color: "#7565fc",
    money: "$516.81",
    mobile: "Android 4.4.2",
  },
  {
    image: "https://robohash.org/quisvoluptatemet.png?size=100x100&set=set1",
    name: "Kienan Loeber",
    color: "Aquamarine",
    hex_color: "#dad32b",
    money: "$838.64",
    mobile: "Android 4.0.4, up to 4.1",
  },
  {
    image: "https://robohash.org/natusoccaecaticum.png?size=100x100&set=set1",
    name: "Bealle Infante",
    color: "Red",
    hex_color: "#388bba",
    money: "$331.21",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/officiisetsapiente.png?size=100x100&set=set1",
    name: "Buck Boundey",
    color: "Fuscia",
    hex_color: "#d8e20e",
    money: "$443.80",
    mobile: "Android 6.0, eUI 5.6",
  },
  {
    image: "https://robohash.org/eosinimpedit.png?size=100x100&set=set1",
    name: "Sheffield Parkhouse",
    color: "Crimson",
    hex_color: "#7edc61",
    money: "$248.95",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/architectovelcum.png?size=100x100&set=set1",
    name: "Chick Gayton",
    color: "Green",
    hex_color: "#a95514",
    money: "$862.97",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/architectoasperioresquia.png?size=100x100&set=set1",
    name: "Foster Coule",
    color: "Goldenrod",
    hex_color: "#76be55",
    money: "$923.79",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/molestiaeatquenesciunt.png?size=100x100&set=set1",
    name: "Codie Youde",
    color: "Turquoise",
    hex_color: "#6b1840",
    money: "$154.53",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/molestiaemolestiasdolore.png?size=100x100&set=set1",
    name: "Winifred Erley",
    color: "Maroon",
    hex_color: "#a62ece",
    money: "$226.71",
    mobile: "Symbian 7.0s, Series 60 v2.0 UI",
  },
  {
    image: "https://robohash.org/nobisnisiid.png?size=100x100&set=set1",
    name: "Chet Gambles",
    color: "Blue",
    hex_color: "#ad2e38",
    money: "$644.65",
    mobile: "Android 5.0",
  },
  {
    image:
      "https://robohash.org/aperiamreiciendisdoloribus.png?size=100x100&set=set1",
    name: "Melba Jeduch",
    color: "Fuscia",
    hex_color: "#b0dfd0",
    money: "$997.45",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/eligendiaccusamusimpedit.png?size=100x100&set=set1",
    name: "Saraann Killgus",
    color: "Mauv",
    hex_color: "#fad714",
    money: "$124.60",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/sintofficiisaccusantium.png?size=100x100&set=set1",
    name: "Janine Alstead",
    color: "Mauv",
    hex_color: "#092a70",
    money: "$133.20",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/adipiscidoloremvoluptatem.png?size=100x100&set=set1",
    name: "Phaedra Belfelt",
    color: "Maroon",
    hex_color: "#a5819c",
    money: "$271.12",
    mobile: "Android 9.0, up to Android 10, LG UX 10.0",
  },
  {
    image:
      "https://robohash.org/istereprehenderitvoluptas.png?size=100x100&set=set1",
    name: "Coleman Lunk",
    color: "Teal",
    hex_color: "#3d868f",
    money: "$395.40",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/harumquasiet.png?size=100x100&set=set1",
    name: "Aaron Domone",
    color: "Pink",
    hex_color: "#2b84cb",
    money: "$600.86",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/reprehenderitautnihil.png?size=100x100&set=set1",
    name: "Tiena Leeuwerink",
    color: "Puce",
    hex_color: "#b3f63a",
    money: "$700.01",
    mobile: "Android 4.0.3",
  },
  {
    image: "https://robohash.org/dolorespariaturest.png?size=100x100&set=set1",
    name: "Pearce Gammack",
    color: "Puce",
    hex_color: "#0dfd62",
    money: "$689.54",
    mobile: "Android 7.0",
  },
  {
    image:
      "https://robohash.org/aperiamrepellatvoluptatem.png?size=100x100&set=set1",
    name: "Siouxie Sommerling",
    color: "Crimson",
    hex_color: "#28c9e7",
    money: "$532.23",
    mobile: "Android 4.4",
  },
  {
    image: "https://robohash.org/quiasuntvoluptates.png?size=100x100&set=set1",
    name: "Mil Sheahan",
    color: "Crimson",
    hex_color: "#1a2302",
    money: "$508.39",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/esteosdolorem.png?size=100x100&set=set1",
    name: "Carree Edington",
    color: "Maroon",
    hex_color: "#59adf3",
    money: "$208.90",
    mobile: "Android 7.0",
  },
  {
    image: "https://robohash.org/hicetconsequatur.png?size=100x100&set=set1",
    name: "Ophelia Bickerdike",
    color: "Fuscia",
    hex_color: "#6572b8",
    money: "$909.73",
    mobile: "Android 4.2.2",
  },
  {
    image: "https://robohash.org/odiomagnamdolores.png?size=100x100&set=set1",
    name: "Roch Mannakee",
    color: "Teal",
    hex_color: "#9749d5",
    money: "$403.04",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/quiaesseiste.png?size=100x100&set=set1",
    name: "Alis Kitchenside",
    color: "Yellow",
    hex_color: "#bca028",
    money: "$250.69",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/quaeratutquas.png?size=100x100&set=set1",
    name: "Gabriella Baggalley",
    color: "Indigo",
    hex_color: "#c207d7",
    money: "$657.71",
    mobile: "Android 4.2",
  },
  {
    image: "https://robohash.org/minusnequevoluptas.png?size=100x100&set=set1",
    name: "Graham Galsworthy",
    color: "Green",
    hex_color: "#a84681",
    money: "$311.21",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/nonmolestiaererum.png?size=100x100&set=set1",
    name: "Kriste Verey",
    color: "Blue",
    hex_color: "#a2507e",
    money: "$88.01",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/illumeligendineque.png?size=100x100&set=set1",
    name: "Patricia Pally",
    color: "Orange",
    hex_color: "#86c614",
    money: "$460.13",
    mobile: "Android 5.0",
  },
  {
    image: "https://robohash.org/eaenimdolore.png?size=100x100&set=set1",
    name: "Webb Rycroft",
    color: "Violet",
    hex_color: "#650d73",
    money: "$279.68",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/omnisutducimus.png?size=100x100&set=set1",
    name: "Christie Pessler",
    color: "Purple",
    hex_color: "#2ab8c9",
    money: "$329.79",
    mobile: "Android 5.1, Cool UI 8",
  },
  {
    image: "https://robohash.org/aspernaturminimavel.png?size=100x100&set=set1",
    name: "Jens Maylour",
    color: "Indigo",
    hex_color: "#2cbc61",
    money: "$114.94",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/rerumaliquidminus.png?size=100x100&set=set1",
    name: "Orland Ledgister",
    color: "Aquamarine",
    hex_color: "#8dd701",
    money: "$577.95",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/iurequiculpa.png?size=100x100&set=set1",
    name: "Morrie Heinert",
    color: "Teal",
    hex_color: "#18f5bb",
    money: "$980.31",
    mobile: "Android 4.2",
  },
  {
    image: "https://robohash.org/quidemrepellatenim.png?size=100x100&set=set1",
    name: "Cyndy Drife",
    color: "Violet",
    hex_color: "#cdad4b",
    money: "$804.47",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/sitaliquidfacilis.png?size=100x100&set=set1",
    name: "Daisi Covill",
    color: "Pink",
    hex_color: "#fc7e07",
    money: "$637.44",
    mobile: "Symbian 6.1, Series 60 v1.0 UI",
  },
  {
    image: "https://robohash.org/velitnonid.png?size=100x100&set=set1",
    name: "Dori Corish",
    color: "Mauv",
    hex_color: "#a46a26",
    money: "$330.11",
    mobile: "watchOS 7.0, up to 7.6",
  },
  {
    image: "https://robohash.org/commodicorruptiunde.png?size=100x100&set=set1",
    name: "Anastasia Bagster",
    color: "Indigo",
    hex_color: "#17a550",
    money: "$801.79",
    mobile: "Android 4.4.2",
  },
  {
    image: "https://robohash.org/easaepeaut.png?size=100x100&set=set1",
    name: "Celestyna Spurrett",
    color: "Turquoise",
    hex_color: "#7a811b",
    money: "$28.55",
    mobile: "Android 4.2",
  },
  {
    image: "https://robohash.org/reiciendisquiaet.png?size=100x100&set=set1",
    name: "Nadean Romaines",
    color: "Puce",
    hex_color: "#e89b4f",
    money: "$474.25",
    mobile: "Android 6.0",
  },
  {
    image:
      "https://robohash.org/namadipisciprovident.png?size=100x100&set=set1",
    name: "Vasily Marquez",
    color: "Fuscia",
    hex_color: "#7b46f4",
    money: "$412.51",
    mobile: "Android 4.2",
  },
  {
    image:
      "https://robohash.org/distinctioporroautem.png?size=100x100&set=set1",
    name: "Corbie Askem",
    color: "Pink",
    hex_color: "#288cc7",
    money: "$277.69",
    mobile: "Microsoft Windows Phone 8.1",
  },
  {
    image: "https://robohash.org/innesciuntnulla.png?size=100x100&set=set1",
    name: "Kahaleel Hugnot",
    color: "Khaki",
    hex_color: "#26afc4",
    money: "$680.84",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/nequefacilisducimus.png?size=100x100&set=set1",
    name: "Millisent Gosker",
    color: "Green",
    hex_color: "#02c534",
    money: "$107.66",
    mobile: "Android 4.4",
  },
  {
    image: "https://robohash.org/quaequoscommodi.png?size=100x100&set=set1",
    name: "Vivyan Easen",
    color: "Puce",
    hex_color: "#b5c311",
    money: "$708.17",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/aliquideostempore.png?size=100x100&set=set1",
    name: "Avie Bolus",
    color: "Green",
    hex_color: "#2bc4e7",
    money: "$142.18",
    mobile: "Android 4.2.2",
  },
  {
    image: "https://robohash.org/beataenonet.png?size=100x100&set=set1",
    name: "Othilia Baccup",
    color: "Indigo",
    hex_color: "#a7280c",
    money: "$258.97",
    mobile: "HP webOS 2.0",
  },
  {
    image: "https://robohash.org/inventorevelest.png?size=100x100&set=set1",
    name: "Merrie Bufton",
    color: "Pink",
    hex_color: "#0182b5",
    money: "$337.57",
    mobile: "Android 5.0, up to 6.0",
  },
  {
    image:
      "https://robohash.org/nesciuntexplicaboaccusamus.png?size=100x100&set=set1",
    name: "Gail Hollow",
    color: "Crimson",
    hex_color: "#b85de4",
    money: "$941.77",
    mobile: "Android 9.0, up to Android 10, Funtouch 10",
  },
  {
    image: "https://robohash.org/anihilquo.png?size=100x100&set=set1",
    name: "Bathsheba Gres",
    color: "Orange",
    hex_color: "#1c707e",
    money: "$145.02",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/voluptatemlaborumdolor.png?size=100x100&set=set1",
    name: "Marysa D'Orsay",
    color: "Red",
    hex_color: "#1b5b65",
    money: "$658.43",
    mobile: "Android 9.0",
  },
  {
    image: "https://robohash.org/doloresnemoqui.png?size=100x100&set=set1",
    name: "Delores Grinham",
    color: "Violet",
    hex_color: "#f786f2",
    money: "$482.39",
    mobile: "Android 9.0, EMUI 9.0",
  },
  {
    image: "https://robohash.org/ipsaatmaiores.png?size=100x100&set=set1",
    name: "Galen Seadon",
    color: "Orange",
    hex_color: "#c9627d",
    money: "$588.96",
    mobile: "Android 8.0, Flyme UI",
  },
  {
    image:
      "https://robohash.org/expeditadoloribusmodi.png?size=100x100&set=set1",
    name: "Orton Orto",
    color: "Purple",
    hex_color: "#c5eb6c",
    money: "$812.94",
    mobile: "Android 5.0.2",
  },
  {
    image:
      "https://robohash.org/nequeperspiciatisquis.png?size=100x100&set=set1",
    name: "Dalenna Raulin",
    color: "Goldenrod",
    hex_color: "#877cce",
    money: "$28.37",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/expeditapariaturet.png?size=100x100&set=set1",
    name: "Madonna de Najera",
    color: "Turquoise",
    hex_color: "#8e8f56",
    money: "$762.10",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/suntassumendaeos.png?size=100x100&set=set1",
    name: "Leena Greenlies",
    color: "Fuscia",
    hex_color: "#9c48cc",
    money: "$170.98",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/aliquidconsequatursoluta.png?size=100x100&set=set1",
    name: "Stesha Cello",
    color: "Teal",
    hex_color: "#867f81",
    money: "$962.46",
    mobile: "Android 6.0, EMUI 4.1",
  },
  {
    image: "https://robohash.org/optioeaquesed.png?size=100x100&set=set1",
    name: "Teodora Hearle",
    color: "Teal",
    hex_color: "#de4464",
    money: "$446.16",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/praesentiumteneturminima.png?size=100x100&set=set1",
    name: "Chrotoem Tremelling",
    color: "Goldenrod",
    hex_color: "#451d91",
    money: "$947.36",
    mobile: "Microsoft Windows Mobile 6 Professional",
  },
  {
    image: "https://robohash.org/accusamusutet.png?size=100x100&set=set1",
    name: "Vikki Cristofano",
    color: "Mauv",
    hex_color: "#ba9b78",
    money: "$572.81",
    mobile: "Android 4.2.2",
  },
  {
    image: "https://robohash.org/fugiatnesciuntnobis.png?size=100x100&set=set1",
    name: "Timmy MacKegg",
    color: "Violet",
    hex_color: "#1c6123",
    money: "$879.22",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/adautducimus.png?size=100x100&set=set1",
    name: "Corrie Jopp",
    color: "Indigo",
    hex_color: "#cdebb2",
    money: "$934.92",
    mobile: "Android 4.4",
  },
  {
    image:
      "https://robohash.org/veniamcumquemolestiae.png?size=100x100&set=set1",
    name: "Edward Shottin",
    color: "Maroon",
    hex_color: "#5a1aa9",
    money: "$415.14",
    mobile: "Microsoft Smartphone 2003 SE",
  },
  {
    image: "https://robohash.org/enimabmaxime.png?size=100x100&set=set1",
    name: "Arabela Bratt",
    color: "Maroon",
    hex_color: "#54e63a",
    money: "$46.23",
    mobile: "Android 9.0",
  },
  {
    image: "https://robohash.org/doloresdolorhic.png?size=100x100&set=set1",
    name: "Nolana Whordley",
    color: "Aquamarine",
    hex_color: "#559037",
    money: "$930.14",
    mobile: "Android 9.0, Fire OS 7",
  },
  {
    image:
      "https://robohash.org/harumoptiovoluptatem.png?size=100x100&set=set1",
    name: "Edik Scud",
    color: "Yellow",
    hex_color: "#e60e3a",
    money: "$848.65",
    mobile: "Android 5.1",
  },
  {
    image: "https://robohash.org/eosnihilet.png?size=100x100&set=set1",
    name: "Jordana Slaney",
    color: "Blue",
    hex_color: "#3079e4",
    money: "$221.72",
    mobile: "Android 2.3.5",
  },
  {
    image: "https://robohash.org/quisestcupiditate.png?size=100x100&set=set1",
    name: "Filippo Bisgrove",
    color: "Aquamarine",
    hex_color: "#3a9299",
    money: "$877.06",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/rationenequea.png?size=100x100&set=set1",
    name: "Bria Fullard",
    color: "Fuscia",
    hex_color: "#78b7d5",
    money: "$215.35",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/delenitievenietquisquam.png?size=100x100&set=set1",
    name: "Kissie Abbets",
    color: "Blue",
    hex_color: "#15238d",
    money: "$333.25",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/consecteturvoluptatemcum.png?size=100x100&set=set1",
    name: "Tilda Drinkel",
    color: "Violet",
    hex_color: "#725ad1",
    money: "$910.24",
    mobile: "Android 4.1.1, up to 4.4.2, Sense UI 5",
  },
  {
    image: "https://robohash.org/estsiteos.png?size=100x100&set=set1",
    name: "Christie Bushby",
    color: "Fuscia",
    hex_color: "#cdeeed",
    money: "$27.88",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/aspernaturatqueaut.png?size=100x100&set=set1",
    name: "Leonidas Ferbrache",
    color: "Orange",
    hex_color: "#542a5d",
    money: "$519.86",
    mobile: "Android 5.1.1, up to 7.0, TouchWiz UI",
  },
  {
    image: "https://robohash.org/delenitieaquae.png?size=100x100&set=set1",
    name: "Maude Clitheroe",
    color: "Puce",
    hex_color: "#d3b1f8",
    money: "$944.05",
    mobile: "Android 9.0, ZUI 11",
  },
  {
    image: "https://robohash.org/adipiscieiusquo.png?size=100x100&set=set1",
    name: "Quillan Sara",
    color: "Green",
    hex_color: "#effb6a",
    money: "$837.19",
    mobile: "Android 4.3, up to 4.4.2",
  },
  {
    image: "https://robohash.org/magnamerrornon.png?size=100x100&set=set1",
    name: "Benni Gardener",
    color: "Orange",
    hex_color: "#e6beea",
    money: "$966.33",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/officiisdistinctiodolorem.png?size=100x100&set=set1",
    name: "Nikaniki Normington",
    color: "Goldenrod",
    hex_color: "#a45934",
    money: "$603.45",
    mobile: "Microsoft Windows Mobile 5.0",
  },
  {
    image: "https://robohash.org/quisomnisdeserunt.png?size=100x100&set=set1",
    name: "Regina Wombwell",
    color: "Violet",
    hex_color: "#846fc6",
    money: "$318.85",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/assumendaconsequaturnumquam.png?size=100x100&set=set1",
    name: "Alleyn Klein",
    color: "Violet",
    hex_color: "#e83f57",
    money: "$991.67",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/eosaccusamusquia.png?size=100x100&set=set1",
    name: "Mark Maleck",
    color: "Maroon",
    hex_color: "#fc35c6",
    money: "$794.43",
    mobile: "Android 4.4, EMUI 3",
  },
  {
    image: "https://robohash.org/aperiametducimus.png?size=100x100&set=set1",
    name: "Purcell Chalcroft",
    color: "Violet",
    hex_color: "#9f6bd5",
    money: "$508.41",
    mobile: "Android 7.1.1, up to 8.0, Funtouch 3.2",
  },
  {
    image: "https://robohash.org/velitetvoluptatum.png?size=100x100&set=set1",
    name: "Shannon McKelvie",
    color: "Fuscia",
    hex_color: "#c45179",
    money: "$259.02",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/temporaexplicaboesse.png?size=100x100&set=set1",
    name: "Alvira Joyes",
    color: "Orange",
    hex_color: "#b6c179",
    money: "$428.85",
    mobile: "Android 10, EMUI 11, no Google Play Services",
  },
  {
    image: "https://robohash.org/inciduntetrerum.png?size=100x100&set=set1",
    name: "Goran Stickings",
    color: "Goldenrod",
    hex_color: "#ffe8d8",
    money: "$636.86",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/molestiasomnisharum.png?size=100x100&set=set1",
    name: "Jemimah Shoosmith",
    color: "Blue",
    hex_color: "#04dfd8",
    money: "$875.55",
    mobile: "Android 4.2",
  },
  {
    image:
      "https://robohash.org/deseruntrerumadipisci.png?size=100x100&set=set1",
    name: "Barr Glasser",
    color: "Fuscia",
    hex_color: "#f72aed",
    money: "$524.08",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/quibusdamlaboriosamquis.png?size=100x100&set=set1",
    name: "Bryna Fley",
    color: "Purple",
    hex_color: "#06bb15",
    money: "$831.77",
    mobile: "bada 2.0",
  },
  {
    image:
      "https://robohash.org/temporibusvoluptatemblanditiis.png?size=100x100&set=set1",
    name: "Marja Burt",
    color: "Fuscia",
    hex_color: "#f2a878",
    money: "$72.31",
    mobile: "Android 5.0",
  },
  {
    image: "https://robohash.org/rerumdoloremerror.png?size=100x100&set=set1",
    name: "Konstanze Charette",
    color: "Fuscia",
    hex_color: "#f8e900",
    money: "$356.97",
    mobile: "Android 4.4.2, TouchWiz UX UI",
  },
  {
    image: "https://robohash.org/quoetnulla.png?size=100x100&set=set1",
    name: "Hyacinth MacTrustram",
    color: "Puce",
    hex_color: "#a5ac6b",
    money: "$947.95",
    mobile: "Android 6.0",
  },
  {
    image: "https://robohash.org/reruminconsequuntur.png?size=100x100&set=set1",
    name: "Graham Morgan",
    color: "Khaki",
    hex_color: "#faf050",
    money: "$170.93",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/quiacumconsequatur.png?size=100x100&set=set1",
    name: "Finlay Heild",
    color: "Red",
    hex_color: "#f900cf",
    money: "$817.63",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/solutaeligendiveritatis.png?size=100x100&set=set1",
    name: "Annamaria Knight",
    color: "Fuscia",
    hex_color: "#37ee64",
    money: "$472.97",
    mobile: "BlackBerry OS",
  },
  {
    image: "https://robohash.org/veritatisestquis.png?size=100x100&set=set1",
    name: "Marchelle Brickell",
    color: "Blue",
    hex_color: "#9942c6",
    money: "$164.87",
    mobile: "Microsoft Windows Phone 8.1",
  },
  {
    image: "https://robohash.org/quitotamnesciunt.png?size=100x100&set=set1",
    name: "Raychel Mechic",
    color: "Fuscia",
    hex_color: "#224c1b",
    money: "$977.87",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/perferendissuntsed.png?size=100x100&set=set1",
    name: "Florentia Mc Menamin",
    color: "Blue",
    hex_color: "#2e2079",
    money: "$273.05",
    mobile: "Microsoft Windows Mobile 6.0 Professional",
  },
  {
    image: "https://robohash.org/sintsuntatque.png?size=100x100&set=set1",
    name: "Venus Jesson",
    color: "Violet",
    hex_color: "#b7c0aa",
    money: "$760.05",
    mobile: "Android 10, up to Android 11, MIUI 12.5",
  },
  {
    image: "https://robohash.org/nonnatusnihil.png?size=100x100&set=set1",
    name: "Leigh MacSwayde",
    color: "Aquamarine",
    hex_color: "#1ce62a",
    money: "$89.92",
    mobile: "Android 8.0, MIUI 9",
  },
  {
    image: "https://robohash.org/totamveroquos.png?size=100x100&set=set1",
    name: "Mira Ridgwell",
    color: "Fuscia",
    hex_color: "#17a180",
    money: "$544.66",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/nesciuntimpeditet.png?size=100x100&set=set1",
    name: "Ermengarde Garmons",
    color: "Purple",
    hex_color: "#dacfad",
    money: "$561.80",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/nonestexpedita.png?size=100x100&set=set1",
    name: "Reinhard Ansett",
    color: "Aquamarine",
    hex_color: "#54077f",
    money: "$587.21",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/eumtemporibuset.png?size=100x100&set=set1",
    name: "Lily Quennell",
    color: "Yellow",
    hex_color: "#83c573",
    money: "$188.10",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/teneturrerumrerum.png?size=100x100&set=set1",
    name: "Celene Whatling",
    color: "Maroon",
    hex_color: "#ea707c",
    money: "$251.85",
    mobile: "Android 5.1",
  },
  {
    image:
      "https://robohash.org/exercitationematquedelectus.png?size=100x100&set=set1",
    name: "Melanie Sheasby",
    color: "Fuscia",
    hex_color: "#62875f",
    money: "$155.44",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/etestesse.png?size=100x100&set=set1",
    name: "Aeriell Humberstone",
    color: "Purple",
    hex_color: "#b425eb",
    money: "$867.30",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/voluptatesfacilisesse.png?size=100x100&set=set1",
    name: "Gustie Jodlowski",
    color: "Violet",
    hex_color: "#b406a8",
    money: "$646.03",
    mobile: "Android 4.4.2",
  },
  {
    image: "https://robohash.org/quiaquasquis.png?size=100x100&set=set1",
    name: "Elmer Harriday",
    color: "Yellow",
    hex_color: "#5c2a2c",
    money: "$717.33",
    mobile: "Android 5.1, MiFavor UI",
  },
  {
    image: "https://robohash.org/etvoluptatibusqui.png?size=100x100&set=set1",
    name: "Cthrine Annes",
    color: "Blue",
    hex_color: "#db6f86",
    money: "$10.20",
    mobile: "Android 4.4.2",
  },
  {
    image:
      "https://robohash.org/laborumvelitrepellat.png?size=100x100&set=set1",
    name: "Conway Seear",
    color: "Mauv",
    hex_color: "#70ce86",
    money: "$597.85",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/autemvoluptatemharum.png?size=100x100&set=set1",
    name: "Cassondra Linwood",
    color: "Turquoise",
    hex_color: "#366921",
    money: "$975.72",
    mobile: "Android 7.1, up to Android 8.1",
  },
  {
    image: "https://robohash.org/voluptatemistererum.png?size=100x100&set=set1",
    name: "Curt McCreary",
    color: "Aquamarine",
    hex_color: "#1f6666",
    money: "$475.48",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/solutarationemodi.png?size=100x100&set=set1",
    name: "Guillaume Lello",
    color: "Maroon",
    hex_color: "#d2891c",
    money: "$318.22",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/delenitietat.png?size=100x100&set=set1",
    name: "Goldarina Stroobant",
    color: "Teal",
    hex_color: "#7d036e",
    money: "$301.84",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/exquofugit.png?size=100x100&set=set1",
    name: "Wendi Goricke",
    color: "Blue",
    hex_color: "#88b553",
    money: "$415.53",
    mobile: "Android 4.2.2",
  },
  {
    image: "https://robohash.org/nobisnamexplicabo.png?size=100x100&set=set1",
    name: "Lukas Howie",
    color: "Purple",
    hex_color: "#2041f5",
    money: "$583.86",
    mobile: "Android 4.2, up to 4.3",
  },
  {
    image:
      "https://robohash.org/consequaturevenietsimilique.png?size=100x100&set=set1",
    name: "Fairleigh Mateu",
    color: "Crimson",
    hex_color: "#b3fa8a",
    money: "$69.04",
    mobile: "Android 10, MiFavor 10.5",
  },
  {
    image: "https://robohash.org/doloresdoloremet.png?size=100x100&set=set1",
    name: "Adina Woodhouse",
    color: "Indigo",
    hex_color: "#ae7481",
    money: "$377.27",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/providentquosed.png?size=100x100&set=set1",
    name: "Mathe Brenston",
    color: "Crimson",
    hex_color: "#ad521d",
    money: "$951.71",
    mobile: "Android 4.4",
  },
  {
    image: "https://robohash.org/quiaidquia.png?size=100x100&set=set1",
    name: "Fairlie Winterburn",
    color: "Purple",
    hex_color: "#1db08c",
    money: "$648.52",
    mobile: "Android 4.4.2, up to 5.0",
  },
  {
    image: "https://robohash.org/suntautsequi.png?size=100x100&set=set1",
    name: "Martainn Groll",
    color: "Violet",
    hex_color: "#807ae5",
    money: "$446.08",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/impeditestvelit.png?size=100x100&set=set1",
    name: "Joceline Barratt",
    color: "Turquoise",
    hex_color: "#031b7c",
    money: "$730.50",
    mobile: "Microsoft Windows Mobile 5.0 PocketPC",
  },
  {
    image: "https://robohash.org/quipariaturcum.png?size=100x100&set=set1",
    name: "Marvin Heaviside",
    color: "Teal",
    hex_color: "#3ecbb6",
    money: "$967.68",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/nullaerrornon.png?size=100x100&set=set1",
    name: "Alysia Gunter",
    color: "Mauv",
    hex_color: "#874166",
    money: "$237.93",
    mobile: "Feature phone",
  },
];
